### ISSUE TITLE
Hey cara estou com dúvida em um código em seu spec_helper.rb

### ISSUE THREAD

**Issue by valterbarros** [ricardovaleriano/foc_ruby_toy_robot#1]
O código é esse aqui ele serve para o que exatamente? 

 `$LOAD_PATH.unshift File.expand_path("../../lib", __FILE__)`

Eu entendo que ele serve para carregar arquivos mas não sei o que exatamente.

Obrigado.

**Comment by ricardovaleriano** [comment]
Fala @valterbarros. Tudo beleza, programista?

_TL;DR_: Essa linha coloca o diretório `lib` no `$LOAD_PATH`.

 - `$LOAD_PATH` é um array com os paths onde o ruby vai procurar seus arquivos quando você usa `require`.
 - [`unshift`](https://ruby-doc.org/core-2.2.0/Array.html#method-i-unshift) coloca um elemento "na frente" em um array (prepend).
 - [`File.expand_path`](https://ruby-doc.org/core-2.2.0/File.html#method-c-expand_path) transforma um caminho relativo em absoluto. O segundo parâmetro é "a partir de onde". Nesse caso, o próprio arquivo `spec_helper`. O primeiro parâmetro, "volta" na estrutura de diretórios até o diretório `lib`.

**Comment by valterbarros** [comment]
Ae cara brigadão!
